#ifndef HS_SRC_CONFIG
#define HS_SRC_CONFIG

#define HAS_MONOID_DOC 1
#define HAS_SHOW_IDENTITY 0
#define HAS_TRAVERSABLE_INTMAP 1
#define HAS_FUNCTOR_TUPLE 1
#define HAS_FUNCTOR_TUPLE3 0
#define HAS_FOLDABLE_TUPLE 1
#define HAS_FOLDABLE_TUPLE3 0

#define USE_READLINE 0
#define USE_EDITLINE 0

#endif
